org: apexwoot
app: articles
service: articles-grabler
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  apiGateway:
    apiKeys:
      - ApiKey

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          private: true
          authorizer: aws_iam
      - http:
          path: /titles
          method: get
          private: true
          cors:
            headers: '*'


